# Generated by Django 4.2.20 on 2025-05-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="questions",
            field=models.TextField(default=""),
        ),
    ]
