# Generated by Django 4.2.20 on 2025-04-23 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pdf", "0001_initial"),
        ("assign", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentPdf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdfs",
                        to="assign.assignment",
                    ),
                ),
                (
                    "pdf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_pdfs",
                        to="pdf.pdf",
                    ),
                ),
            ],
        ),
    ]
