# Generated by Django 4.2.20 on 2025-04-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_conversationtemplate_conversation_template"),
        ("assign", "0002_assignmentpdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="conversation_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="chat.conversationtemplate",
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="conversation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homework",
                to="chat.conversation",
            ),
        ),
    ]
