# Generated by Django 4.2.20 on 2025-04-26 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_conversationtemplate_conversation_template"),
        ("judge", "0002_submission_success_count_submission_total_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_conversations",
                        to="chat.conversation",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="judge.problem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProblemMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src", models.TextField(blank=True, null=True)),
                ("lang", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_message",
                        to="chat.message",
                    ),
                ),
                (
                    "problem_conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="judge.problemconversation",
                    ),
                ),
                (
                    "relevant_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_messages",
                        to="judge.submission",
                    ),
                ),
                (
                    "start_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="successive_questions",
                        to="judge.problemmessage",
                    ),
                ),
            ],
        ),
    ]
