# Generated by Django 4.2.20 on 2025-03-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="tokens",
            field=models.IntegerField(default=0),
        ),
    ]
