# Generated by Django 4.2.20 on 2025-03-21 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_message_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
