# Generated by Django 4.2.20 on 2025-04-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_conversationtemplate_conversation_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="starters",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="conversation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
